### PR TITLE
WIP: Travis fixes

### PR DESCRIPTION
**Pull request by snecklifter**
Testing to see if I can help fix travis builds :)

### CODE REVIEW

**Comment by pepijnve** [comment]
No need to worry about Travis and Appveyor builds. I'm in the process of getting rid of those and transitioning to GitHub Actions. The Windows Actions build still has issues, but the Linux stuff replaces Travis already. I'll get rid of the YAML file already.

**Comment by snecklifter** [comment]
@pepijnve ok, well, it was fun debugging it anyway. Looks like I fixed/worked around by pinning the node version. The Windows build looks like appveyor still looking for an old version of ImageMagick from the chocolatey release. Trying to figure out how to tell it to get the latest build as it seems its getting a cached copy.

**Comment by pepijnve** [comment]
If you have the time and motivation, help with the Actions Windows build is welcome. My work-in-progress/trial-and-error stuff is on the `windows` branch.

**Comment by snecklifter** [comment]
@pepijnve sure, I'll take a look and help if I can

**Comment by snecklifter** [comment]
@pepijnve would be helpful to get write access on that branch so I can re-run workflows, if possible.

**Pull request closed without merging**
