### PR TITLE
Support for gnuplot mathemathical plots

### PR DESCRIPTION
**Pull request by MariuszCwikla**
Hi,
I would like to propose integration with gnuplot http://gnuplot.info/ - a tool to draw mathemathical functions

Demo galleries:

* http://gnuplot.sourceforge.net/demo_5.2/
* https://commons.wikimedia.org/wiki/Category:Gnuplot_diagrams

Some tips about my implementation approach:

* Default gnuplot behavior is to display chart in GUI window, but there are multiple ways to control output, including output to stdout.
I am utilizing `set term png size 1024,768` command which outputs to stdout.

* I've implemented png/svg formats now
* additional attributes: width/height (default 1024x768)

Working example:

```
[gnuplot, complexity, svg]
....
unset tics; 

log2(x)=log(x)/log(2)

set linetype 1 lw 6
set linetype 2 lw 6
set linetype 3 lw 6
set linetype 4 lw 6
set linetype 5 lw 6
set linetype 6 lw 6

set key opaque left

set xlabel 'Input Size(n)'
set ylabel 'Time or Space'

set title 'Algorithm Complexity'

plot [0:10][0:10] x title 'O(n)',\
x**2 title 'O(n^2)' ,\
x**3 title 'O(n^3)' ,\
log2(x) title 'O(log n)' ,\
x * log2(x) title 'O(n log(n))' ,\
1 title 'O(1)'
....
```

If you like it, I'd be happy to write some docs later.

### CODE REVIEW

**Comment by pepijnve** [comment]
Looks good. Thanks for this addition.

Just one question about the size. Should we default to the gnuplot defaults when `width`/`height` are unspecified instead of having asciidoctor choose its own defaults? That would require omitting the `size` terminal parameter.

It might also be nice to expose some other terminal options like `(no)transparent`, `(no)crop`, `font`, ..., but that can be done as a separate enhancement.

**Comment by MariuszCwikla** [comment]
@pepijnve thanks for your suggestions
1. default size - sounds good. I've updated code
2. other options sounds good too. I'll make an enhancement.

**Comment by MariuszCwikla** [comment]
@pepijnve I've added some changes:

- updated docs
- support for gif, txt (in addition to png, svg)
- added attributes you suggested and couple more (`crop`, `transparent`, `background`, `font`, `fontscale`)

Regarding attributes - not all attributes are supported for all formats.
Furthermore some formats support even more attributes, but I am not sure if it makes sense to implement all of them.

You can check it by yourself by running:

```
gnuplot> help set term png
gnuplot> help set term svg
gnuplot> help set term gif
gnuplot> help set term txt
```

gnuplot supports generating pdfs too (see `help set term pdfcairo`) but I think that pdf rendering broken anyway somewhere in asciidoctor-diagram (I've tested it with graphviz; probably I should report an issue for this)

**Comment by pepijnve** [comment]
Hi @MariuszCwikla 
Thanks for the updates. I’ve been pretty swamped this week with my day job so I haven’t had a chance to review the pr changes yet. I’ll try to get this merged over the weekend.

**Pull request merged**
