### PR TITLE
Fix puppeteerConfig related issues

### PR DESCRIPTION
**Pull request by ldz-w**
Fix an issue with the `puppeteerConfig` options introduced in #251

### CODE REVIEW

**Comment by pepijnve** [comment]
Is this actually a bug? I agree that the hash key names are a bit confusing, but the previous code was correct afaict.

**Comment by ldz-w** [comment]
Bug - I don't know. However, for some reason, in my project it only works with this commit. 
I can't say much due to lack of familiarity with the code base. 

I am using my personal fork as part of my project setup right now and it works. It didn't before.
More specifically `:mermaid-puppeteerConfig:`didn't work. 

Maybe you have some insight as to why it didn't looking at it now.

**Comment by pepijnve** [comment]
Fixed by d93249e instead. The root cause was document attributes being normalised to lowercase by asciidoctor core.

**Comment by mojavelinux** [comment]
Attribute names should be lowercase.

**Comment by pepijnve** [comment]
> Attribute names should be lowercase.

@mojavelinux if you enter a block attribute in upper case or mixed case, it's passed to the extension as is while document attributes seem to get lowercased before being added to the attributes hash. Is the block behaviour expected or should that be considered a bug (or omission if you will) in core?

**Comment by mojavelinux** [comment]
That distinction predated my involvement in AsciiDoc. It was likely an
oversight to lowercase one but not the other. Likely it was never noticed
because all attributes were always defined in lowercase. That's the best
practice. So while they could be forced to lowercase, it's better just to
avoid the situation. It is certainly something that needs to be discussed
in the spec.

**Comment by pepijnve** [comment]
Ok, thanks for the background info. I've solved this by normalising to lowercase in the extension (see 4c3df0108ea2851d138d36c432868897aaab761a). This way the converter implementations don't need to care either way.

**Comment by mojavelinux** [comment]
Perfect. Though I'd still recommend also using kabob case for multiple words (e.g., puppeteer-config).

**Comment by pepijnve** [comment]
I adapted the converters that needed this to support that style as well along with the camel case they already expected. I'll update the attribute lists in the README as well so that it's clear the dash style is recommended.

**Pull request closed without merging**
