### PR TITLE
Fixes #147 - adds support for plantuml math and svg output.

### LINKED ISSUE #147: Add additional jars to support svg and math output for plantuml, and upgrade plantuml.
I've created a corresponding pull request that includes the jar files and the relevant licenses.  Details will be included in pull request.

### PR DESCRIPTION
**Pull request by puffybsd**
Bumps plantuml version to 8059.
Note that plantuml.jar references the batik-all-1.7.jar and
jlatexmath-minimal-1.0.3.jar files through the Class-Path attribute
in the MANIFEST.MF file, so file names must match, and there's no need
to include a reference to them in the plantuml extension.rb.

### CODE REVIEW

**Comment by pepijnve** [comment]
@puffybsd thanks for the contribution, but I'm afraid I can't integrate this. jlatexmath is GPLv2 licensed. Bundling that with asciidoctor-diagram creates a derived work of jlatexmath which means the whole would be been to be GPLv2 licensed as well. asciidoctor-diagram is MIT licensed at the moment and I'm not willing to switch it to GPL.

**Comment by puffybsd** [comment]
@pepijnve that's understandable.  There is a clause that the authors have added, would you mind taking a look at it and determining if it makes any difference?  If it doesn't, might I suggest that I break out the jlatexmath portion from the batik aspect, so that svg format can still be used for diagram generation, and substitute instructions for linking to jlatexmath for anyone interested?
```
 33   As a special exception, the copyright holders of this library give you 
 34 permission to link this library with independent modules to produce 
 35 an executable, regardless of the license terms of these independent 
 36 modules, and to copy and distribute the resulting executable under terms 
 37 of your choice, provided that you also meet, for each linked independent 
 38 module, the terms and conditions of the license of that module. 
 39 An independent module is a module which is not derived from or based 
 40 on this library. If you modify this library, you may extend this exception 
 41 to your version of the library, but you are not obliged to do so. 
 42 If you do not wish to do so, delete this exception statement from your 
 43 version.
```

**Comment by puffybsd** [comment]
Here's the relevant discussion where the authors have modified the license to include the exception text:
https://forge.scilab.org/index.php/p/jlatexmath/issues/1566

**Comment by mojavelinux** [comment]
I'd really like to find a way for us to enable this capability because it would be huge for this community. If we need advise on the OSS legal side, I have connections who could help.

**Comment by pepijnve** [comment]
I had missed the classpath exception bit when scanning the license. With those extra clauses I don't think there are any licensing issues.

Only con I can see is that the gem size will grow significantly again. If you're ok with that I think we can proceed with this.

**Comment by mojavelinux** [comment]
For this gem, I don't see too much drawback from a large file size. There's an understanding that the extension pulls in diagram applications.

To deal with file growth in the future, we might consider moving to distributing the bundled libraries themselves as separate gems which are optional dependencies. That's how other projects handle this sort of thing.

**Comment by pepijnve** [comment]
@puffybsd it looks like the plantuml jar you included is the GPL licensed version as well. Could you switch that to the latest ASL licensed one instead? http://sourceforge.net/projects/plantuml/files/plantuml-jar-asl-2017.10.zip/download

We're also going to have to update the classpath definition at https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/plantuml/extension.rb#L13.
The classpath from a JAR file's manifest is only used when you run `java -jar <jar file>`. Asciidoctor-diagram doesn't launch Java that way so we do need to list the jars explicitly.

@mojavelinux I think integration with jlatexmath would be very useful to get offline math rendering to bitmap or vector images. Just wondering if the plantuml support is the most useful way to do this. Some kind of integration with asciidoc's builtin math sections seems more useful. Is there any way asciidoctor-diagram could (optionally) intercept processing of math sections and render them to images without requiring users to change their documents to use `plantuml` and `@startmath`?

**Comment by puffybsd** [comment]
Sure, will update jar for license this evening.  I didn't need to update the class path to test, can you give it a try without?

**Comment by pepijnve** [comment]
Perhaps I'm mistaken with the `Class-Path` thing. As long as it works I'm good with it.
Could you add a minimal test case that exercises the new functionality? That way Travis will run it against all supported Ruby runtimes and we'll be 100% sure it works correctly in all cases.

**Comment by puffybsd** [comment]
@pepijnve: made progress on the ASL version, but haven't gotten the existing tests to run. On arch linux, the meme test hangs indefinitely.  Once I get the existing tests running, I'll add some tests and resubmit the PR.

Due to method signature changes in plantuml, I've had to go with the 8059 ASL version for now.

```bash
[puffybsd@dal asciidoctor-diagram]$ java -jar lib/plantuml.jar -version
PlantUML version 8059 (Wed Mar 15 13:37:07 EDT 2017)
(APACHE source distribution)
...
```
And here's a diff of the commit between 8059 and the next version (grep for SourceStringReader) if you are interested:
https://github.com/plantuml/plantuml/commit/091a95bd8289b3af736901f11c2da171fc95b1d8
generateimage_string_to_diagramdescriptor

**Comment by puffybsd** [comment]
The plantuml_spec.rb tests run fine by themselves.  I'll add some additional tests there and send an update.

**Comment by pepijnve** [comment]
@puffybsd the Java glue code that interfaces with PlantUML is located at https://github.com/pepijnve/asciidoctor-diagram-java. We'll need to get that updated to be able to upgrade to the latest PlantUML build then. I'll take care of that in a separate changeset.

@mojavelinux could you transfer that repository over to the asciidoctor organisation. It's a part of the asciidoctor-diagram project so it makes sense to keep the two together.

**Comment by mojavelinux** [comment]
@pepijnve :+1:  You should be able to transfer the repository now. I enabled the transfer permission.

**Comment by mojavelinux** [comment]
> I think integration with jlatexmath would be very useful to get offline math rendering to bitmap or vector images.

:+1:

> Just wondering if the plantuml support is the most useful way to do this.

Good question. I think it really depends on the users and whether they find this to be easy and advantageous.

>  Some kind of integration with asciidoc's builtin math sections seems more useful. Is there any way asciidoctor-diagram could (optionally) intercept processing of math sections and render them to images 

Absolutely. This could essentially become an alternate to [asciidoctor-mathematical](https://github.com/asciidoctor/asciidoctor-mathematical/). Perhaps something like asciidoctor-plantmath or asciidoctor-jlatexmath. The logic would essentially be the same. 

A Java-based approach would be much more portable than mathematical, which requires numerous C libraries.

> without requiring users to change their documents to use plantuml and @startmath?

If we add math support to the plantuml integration, we should make it clear that it is for use of math *in* diagrams and not as an alternative to stem blocks. For that, users really should depend on a dedicated extension.

**Comment by pepijnve** [comment]
@mojavelinux thanks for the pointer to asciidoctor-mathematical. That provides a good example of how to process stem blocks with a tree processor extension.
How about adding an extra opt-in tree processor extension to diagram as well that uses jlatexmath to generate images the same way mathematical does? That way we don't have to duplicate all the Java VM logic. By opt-in I mean it wouldn't be included in https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram.rb, you would have to require `asciidoctor-diagram/math` explicitly.

**Comment by pepijnve** [comment]
@mojavelinux -java project has been transferred, but I stupidly locked myself out now 🤦‍♂️  Could you change the access settings?

**Comment by mojavelinux** [comment]
@pepijnve All fixed. Don't worry, it's not you, it's GitHub. They can't seem to implement a workflow for transferring repositories that makes any sense. So I always have to go in and fix what they messed up.

**Comment by puffybsd** [comment]
@pepijnve updated the PR to include the ASL version, 8059, and some specs for latex.
One of the benefits of having the jlatexmath available for asciidoctor-diagram is that it allows math and latex within the diagrams using the `<latex>` tag.  This is fairly handy when combined with svg support and seems to be a unique feature.  There seems to be a issue with asciimath support, I'll investigate as a separate issue as time permits.

**Comment by pepijnve** [comment]
I've gone ahead and merged this PR already.
In the meantime I'm continuing work on this in asciidoctor-diagram-java. I've already made it possible to load each Java based diagram generator as a service using ServiceLoader. The makes the Java code more extensible.
Next step will be to split the asciidoctor-diagram gem into multiple gems, a core plus one per diagram type. The current asciidoctor-diagram gem will simply list dependencies on all the gems that cover the functionality provided by the current gem.
I'll write up a proper description of this work in an issue later.

**Pull request merged**
