### PR TITLE
#116 Resolve relative paths in PlantUML !include directives

### PR DESCRIPTION
**Pull request by pepijnve**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Good work.

It's actually more correct to make the include relative to the value of the docdir attribute rather than the base_dir. While this is still an area of improvement for core, base_dir is really an internal construct that more or less serves as the chroot jail. The improvement to core is to separate jail, base and docdir into three separate settings.

**Comment by mojavelinux** [comment]
:+1: Nice work.

Am I correct in saying the following?

- if the diagram in an external file, includes are resolved relative to that external file
- if the diagram is embedded in the AsciiDoc, includes are resolved relative to the AsciiDoc file

If correct, can you add these to the README?

**Comment by pepijnve** [comment]
Yes that's correct. This way relative paths are resolved wrt the document in which they're defined. Seemed easiest to understand/explain.

**Comment by mojavelinux** [comment]
Perfect. I love it. :beers:

**Pull request merged**
