### PR TITLE
translate README to Chinese

### PR DESCRIPTION
**Pull request by diguage**

### CODE REVIEW

**Comment by diguage** [comment]
Why have all checks failed?

**Comment by pepijnve** [comment]
Unrelated issues. Trying to get all tests working on Travis and Appveyor. That requires two versions of phantomjs in parallel.

**Comment by pepijnve** [comment]
Thanks for making this translation btw. I'm a little bit reluctant to merge this since it's something I can't maintain myself and I'm worried it will be out of sync with the English README all the time.
@mojavelinux do you have translations for Asciidoctor documentation? If so, how do you keep all translations in sync?

**Comment by diguage** [comment]
I like Asciidoctor. Now, I write my documents with Asciidoctor. So, I'll keep Chinese translations in sync.

I want to introduce Asciidoctor to Chinese poeple. So I am translating all the Asciidoctor documents to Chinese.  <https://github.com/asciidoctor/asciidoctor.org/pull/585>

**Comment by mojavelinux** [comment]
If found the secret to keeping translations up to date is simply a good relationship with the community. There's no silver bullet, aside from dedicated people. Human powered ;)

I asked @diguage to send the translation here as part of an ongoing effort to add translations to asciidoctor.org. I would much rather have the translation in the upstream project than sitting downstream in asciidoctor.org, which really should just be a documentation aggregator. 

To help make it clear who the current maintainer of the translation is, it's important to have the field "translator" (or "translators") in the AsciiDoc header, perhaps even shown at the top of the page like we do at http://arquillian.org/guides/getting_started_zh_cn/. If an issue comes in to update the README, just mention the translator to give that person a chance to update.

**Comment by diguage** [comment]
I added the issue about translator field <https://github.com/asciidoctor/asciidoctor/issues/1755>.

**Comment by mojavelinux** [comment]
You don't need to wait on a change in core to add the translators. Just add it to the metadata to the header:

```
:translators: D瓜哥
```

Then reference it somewhere in the text:

```
ifdef::env-github[Translated by: {translators}]
```

When we render it on the website, we might decide to place it somewhere more strategic, which is why I put it behind a conditional.

**Comment by mojavelinux** [comment]
What's important is to get the information into the document. We can always deal with how we show it later.

**Comment by diguage** [comment]
The checks have failed. How to resolve the problem?

**Comment by pepijnve** [comment]
You don't need to fix these. These are due to failures on master that I need to fix.

**Comment by diguage** [comment]
There is the  discussion about the disclamer: <https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/223>

**Comment by pepijnve** [comment]
Sorry for the delay in merging this PR. I've been swamped with other tasks and simply didn't find the time to get this done until now.

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
