### PR TITLE
Add cachedir explanation to README

### PR DESCRIPTION
**Pull request by abelsromero**

### CODE REVIEW

**Comment by abelsromero** [comment]
Let me know if it's correct, I don't fully understand the Ruby code (yet)

**Comment by pepijnve** [comment]
>  I don't fully understand the Ruby code (yet)

Anything in particular you have questions about?

**Comment by pepijnve** [comment]
The description is not quite correct. The default behaviour is to write the cache files into a `.asciidoctor/diagram` subdirectory in the output directory.

**Comment by abelsromero** [comment]
Added the correction ana changed 
`\{base_dir\}/\{imagesdir\}`
by
`\{outdir\}/\{imagesdir\}`

Because checking the code I see the method is called passing outdir, even when the function param is called base_dir https://github.com/asciidoctor/asciidoctor-diagram/blob/fd8ab7d9eb9d5de3c55a0e27c4276206c728a917/lib/asciidoctor-diagram/diagram_processor.rb#L276

**Comment by abelsromero** [comment]
ping...

**Pull request merged**
