### PR TITLE
Update PlantUML to version 8020

### PR DESCRIPTION
**Pull request by j-manu**
The PlantUML included in the gem (Version 8004) fails when `detach` is used. The latest PlantUML  (Version 8020) handles it correctly. Sample code to reproduce

```
@startuml

:start;
if (Should Redirect?) then (yes)
  :Redirect;
  stop
else (no)
  :Process Content;
  detach
endif

@enduml
```

### CODE REVIEW

**Comment by pepijnve** [comment]
@j-manu is this the Apache licensed version of plantuml or the LGPL one? Up until now I've been including the ASL version and would prefer to keep it that way.

**Comment by j-manu** [comment]
@pepijnve I didn't even know there were two versions :) It was the default version which was GPL. I have replaced it with the ASL version

**Comment by j-manu** [comment]
@pepijnve The travis failure is due to https://github.com/travis-ci/travis-ci/issues/3239. I've opened another PR with a fix for that

**Comment by mojavelinux** [comment]
:+1:

**Pull request closed without merging**
