### PR TITLE
Update PlantUML to 1.2022.12

### PR DESCRIPTION
**Pull request by thirtque**
Just updating PlantUML to 1.2022.12 as it adds some new features I would like to use.

Used the ~~MIT~~ ASL license version from the [download page](https://plantuml.com/download).

### CODE REVIEW

**Comment by pepijnve** [comment]
I think up until now I've been using the Apache licensed one. Not sure what the functional difference (if any) there is wrt the MIT one.

**Comment by thirtque** [comment]
I see that in the `LICENSE.txt` you use MIT, but probably there is no difference in the binary itself.

**Comment by thirtque** [comment]
Ok, just now noticed `plantuml-license.txt`. Should be ok now.

**Comment by owbear** [comment]
Anything we can do to get this through? Our pipeline fails with the older plantuml included now:

```
FIL@0 <-> @80 : (filtering time = 80 ms)                                                                                                         
^^^^^                                                                                                                                            
 You should send a mail to plantuml@gmail.com or post to http://plantuml.com/qa with this log (V1.2022.5) java.lang.UnsupportedOperationException
```

Due to https://forum.plantuml.net/16197/timing-diagram-adding-double-arrows-to-analog-signal-type fixed in V1.2022.7

**Comment by pepijnve** [comment]
@owbear if you're blocked on this, there's always the option of using an external plantuml jar instead of the builtin one via the `DIAGRAM_PLANTUML_CLASSPATH` environment variable.

I'll get this merged and published asap. Nothing was really holding this back except availability of spare time on my end.

**Pull request merged**
