### PR TITLE
Fixed #78: Added support for cygwin

### LINKED ISSUE #78: Can't get to run on windows
Just tried to install on windows+cygwin, but can't get it to work. I'm not sure if this is my instalation problem or i have found a bug.

My instalation procedure (from cygwin prompt):
```
$ apt-cyg install graphviz
$ apt-cyg install rubygems
$ gem install ascii-doctor-diagram
$ cd my-project-dir
$ asciidoctor -r asciidoctor-diagram Test.adoc
Error: Could not find or load main class org.asciidoctor.diagram.CommandServer
asciidoctor-diagram: ERROR: Failed to generate image: end of file reached
$ cd ~/.gem/ruby/gems/asciidoctor-diagram-1.3.0/examples
$ asciidoctor -r asciidoctor-diagram -I ../lib design.adoc
Error: Could not find or load main class org.asciidoctor.diagram.CommandServer
asciidoctor-diagram: ERROR: Failed to generate image: end of file reached
Error: Could not find or load main class org.asciidoctor.diagram.CommandServer
asciidoctor-diagram: ERROR: Failed to generate image: end of file reached
```

My version is:
```
$ gem list

*** LOCAL GEMS ***

asciidoctor (1.5.2)
asciidoctor-diagram (1.3.0)
json (1.8.2)
minitest (5.4.3)
power_assert (0.2.2)
rake (10.4.2)
rdoc (4.2.0)
test-unit (3.0.8)
```

### PR DESCRIPTION
**Pull request by chanibal**

### CODE REVIEW

**Comment by chanibal** [comment]
AppVeyor failed not because of my commit but a network timeout on preparing the environment:

    graphviz.portable v2.38
     Attempt to get headers for http://www.graphviz.org/pub/graphviz/stable/windows/graphviz-2.38.zip failed.
       Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
     Downloading graphviz.portable 32 bit
       from 'http://www.graphviz.org/pub/graphviz/stable/windows/graphviz-2.38.zip'
     Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the
      remote server"
     At C:\ProgramData\chocolatey\helpers\functions\Get-WebFile.ps1:66 char:3
     +   $res = $req.GetResponse();
     +   ~~~~~~~~~~~~~~~~~~~~~~~~~

Please rerun

**Comment by pepijnve** [comment]
Change looks good; I'll try to get this integrated this evening.

Don't worry about the appveyor stuff. That happens quite often.

**Comment by pepijnve** [comment]
Thinking about this further, there's just one comment. Now you're using the presence of cygpath on the path as a heuristic to determine that we're running under cygwin's shell. I would instead use rbconfig to check the host platform. That way, when you're running with a native Windows build of Ruby (like the rubyinstaller.org one) and have cygwin's bin folder on the path we won't end up incorrectly triggering the cygpath stuff.

Could you add a `require rbconfig` and `RbConfig::CONFIG['host_os'] =~ /cygwin/i` check around the cygwin code?

**Comment by chanibal** [comment]
Will have to check this with normal ruby too

**Comment by chanibal** [comment]
Can't run this on my local windows ruby install (asciidoctor -r asciidoctor-diagram doc.adoc fails with "invalid style for paragraph: plantuml"?), but the CI tests seem fine.

In the evening i'll check on my win10+cygwin install at home to ensure it works there.

**Comment by chanibal** [comment]
Sorry for the wait. Seems to work fine on cygwin windows10. Unit tests went fine too (well, except for network errors).

**Comment by mojavelinux** [comment]
That's great news!

**Comment by chanibal** [comment]
So, any chance for that merge? Just wanted to install on a different machine and I'm too lazy to apply my patch manually again.

**Comment by pepijnve** [comment]
@chanibal sorry last track of this. I've just merged this PR. I'll add a release note and make a new build right away.

**Comment by pepijnve** [comment]
@chanibal 1.3.1 has been uploaded to rubygems.org. Only change wrt 1.3.0 is this fix.

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
