### PR TITLE
Add support for graphviz-py

### PR DESCRIPTION
**Pull request by Alwinator**
[graphviz-py](https://github.com/Alwinator/graphviz-py) makes it possible to run Python code inside of Graphviz diagrams, as well as using variables. I extended asciidoctor-diagram to support it.

### CODE REVIEW

**Review by pepijnve — APPROVED** [review]
Looks good to me. Thanks for the contribution!

**Comment by Alwinator** [comment]
@pepijnve You are welcome! Thanks for approving my code!

**Comment by pepijnve** [comment]
I had a look at your graphviz-py project in detail this morning. I'm wondering if an extra integration is actually necessary here. Since you support the same CLI interface as `dot` you could also just point the existing graphviz integration to graphviz-py. You can do that by setting the `dot` document attribute (e.g. pass `-a dot=/usr/bin/graphviz-py` to the Asciidoctor CLI).

**Comment by Alwinator** [comment]
@pepijnve Thank you so much for the reminder! I forgot to add an argument for variables. This makes it possible to calculate the same diagram with different values. I think that is very convenient.

```asciidoc

[graphviz_py, "graphviz_py_example", "SVG", argument="foo=5;bar=7"]
----
include::my_diagram.py.dot[]
----

[graphviz_py, "graphviz_py_example", "SVG", argument="foo=24;bar=32"]
----
include::my_diagram.py.dot[]
----
```

**Comment by Alwinator** [comment]
From my side, it is ready for merging now!

**Comment by Alwinator** [comment]
@pepijnve Thank you for merging! I am looking forward to the new version :)

**Comment by pepijnve** [comment]
I'm picking up maintenance work again after a bit of a hiatus. A new release should be ready later today.

**Comment by Alwinator** [comment]
@pepijnve Thank you! That is great!

**Pull request merged**
