### PR TITLE
Build against recent version of Ruby

### PR DESCRIPTION
**Pull request by Mogztter**
The build is failing on my workspace with Ruby 2.4.1.
I think we should only test against recent (and supported) versions of Ruby.

### CODE REVIEW

**Comment by pepijnve** [comment]
@mojavelinux wdyt? I kept Ruby all the way back to 1.8 around since that's the minimum version asciidoctor itself supports.

**Comment by Mogztter** [comment]
Yes, I think we should also adopt semantic versioning in this project once Asciidoctor 2.0.0 will be released.
Arguably you are less coupled to Asciidoctor core so it should be fine.

**Comment by pepijnve** [comment]
@Mogztter Could you change the version to 2.0.0.pre1 as part of this PR then. I want to avoid accidentally shipping a 1.5.x release that drops old ruby support.

**Comment by Mogztter** [comment]
@pepijnve It seems that the build is broken on master:

* bundler 2 seems to be the default version and is not compatible with old Ruby versions
* we are using a method that was renamed on Asciidoctor core master

I'm trying to fix this two issues first.

**Comment by mojavelinux** [comment]
> @mojavelinux wdyt? I kept Ruby all the way back to 1.8 around since that's the minimum version asciidoctor itself supports.

Times are a changin'! See https://asciidoctor.org/news/2018/12/31/making-the-switch-to-semver/. Asciidoctor 2.0 will drop support for Ruby < 2.3 and we'll follow the Ruby release cycle from now on (which means 2.3 will be dropped in March 2019).

**Pull request merged**
